// <auto-generated />
namespace Zkly.DAL.Migrations.User
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TColumnApplyQuota : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TColumnApplyQuota));
        
        string IMigrationMetadata.Id
        {
            get { return "201508310731222_TColumnApplyQuota"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
