// <auto-generated />
namespace Zkly.DAL.Migrations.Config
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class R0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(R0));
        
        string IMigrationMetadata.Id
        {
            get { return "201505081132384_R0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
